### ISSUE TITLE
Impossible 4th Keep Puzzle

### ISSUE THREAD

**Issue by 1234567890num** [sigma144/witness-randomizer#10]
![impossible_1](https://user-images.githubusercontent.com/53823593/76589423-a3cf8f80-651c-11ea-8fb1-c76549c609fa.png)

Expert 18071

The obvious solution can't be reached (since there's no way to get to the other side), and even the solver can't see the solution that involves the bottom line. Doesn't seem like your hint in the wiki can help for this.

**Comment by sigma144** [comment]
Hi there 1234567890num, thanks for playing my mod! There is indeed a way to get across to the other side. I'm guessing your "obvious solution" is actually the correct one. Click below to see the solution:
<details>
<summary>Solution</summary>

**Go along the right side wall, up to the exit on the right, then walk the path backwards, ending at the start in the upper-right.**

![Capture](https://user-images.githubusercontent.com/3487299/76710533-b1cd0e00-66de-11ea-8fa9-6e46a21bd96d.PNG)

</details>

Congrats on getting so far in Expert, and good luck with the rest of the puzzles!
