### ISSUE TITLE
Missing Puzzles

### ISSUE THREAD

**Issue by brddsfnhsdfbjs** [sigma144/witness-randomizer#100]
I am trying to do all 523 panels, but I am faced with this, unsure why.
I am on expert, not double mode, seed: 2123279
Thanks!

![Screenshot 2024-08-16 093635](https://github.com/user-attachments/assets/1d7b8cbf-a557-478e-bfba-665b42b2d809)

**Comment by brddsfnhsdfbjs** [comment]
I'll leave this here in case anyone has this problem, but I have determined it is because my save file used to be on expert double, but is now on just expert.

I managed to fix it by changing the save file back to expert double, and resolving all the active puzzles, which activated the inactivate ones.

**Comment by sigma144** [comment]
Glad you figured it out! Switching modes in the middle of a run can tend to cause weird things to happen.
