### ISSUE TITLE
Sun and arrows panel acts as if suns don't exist

### ISSUE THREAD

**Issue by medicatedshawnie** [sigma144/witness-randomizer#11]
Expert Seed 18937, Bottom floor of caves, second to last panel on the left down the minecart tracks:
Some accepted solutions shows below:
![SOLUTION_11](https://user-images.githubusercontent.com/60412657/77814375-e6e64280-7086-11ea-84e8-8bb35cb83af4.png)
![SOLUTION_22](https://user-images.githubusercontent.com/60412657/77814376-e77ed900-7086-11ea-9f07-c5003d375636.png)
![SOLUTION_33](https://user-images.githubusercontent.com/60412657/77814377-e77ed900-7086-11ea-92dc-a9e8000e5fca.png)

**Comment by sigma144** [comment]
Wow, nice catch medicatedshawnie! Fixed in commit 13a4725. Luckily, this seems to be the only puzzle affected, so you should be able to go about the rest of the game no problem.
