### ISSUE TITLE
(Visual Bug) Hidden Sun & Color at Treehouse?

### ISSUE THREAD

**Issue by gomamisomix** [sigma144/witness-randomizer#14]
Expert 41617 (but file name is 'puzzledataE416170.dat')

I found this puzzle at Treehouse, obviously this is impossible.
![20200813133255_1](https://user-images.githubusercontent.com/5131918/90094933-34c7c280-dd6a-11ea-866d-0eee6742dfda.jpg)

So I made a deliberate mistake,  there were two suns hidden. but I couldn't  decide what color these sun is.
![20200813133000_1](https://user-images.githubusercontent.com/5131918/90094967-5032cd80-dd6a-11ea-88e1-05363c46834c.jpg)

This is the solution. But I don't know what black suns mean & why 3 suns share the same space?
![20200813132954_1](https://user-images.githubusercontent.com/5131918/90094923-2c6f8780-dd6a-11ea-9d0e-30b062458421.jpg)

Is this new additional puzzle for expert mode?

**Comment by sigma144** [comment]
Hi gomamisomix, thanks for playing my mod! That is a visual glitch that I've seen before. It's hard to reproduce and I'm still trying to figure out why it happens. If you close and relaunch the game, then randomize, it should go away. I'm going to leave this issue open just to remind myself that it is still happening.

**Comment by gomamisomix** [comment]
Thanks for the reply. I relaunched the game but it was exactly the same :p
I recorded the process of randomizing.
[https://www.youtube.com/watch?v=UEidjYRWqtI](https://www.youtube.com/watch?v=UEidjYRWqtI)
0:15 randamize again and same glitch was shown.
0:40 I also found a similar bug in another panel.

I hope you can figure out the cause of this bug.

**Comment by sigma144** [comment]
I think I actually figured it out! I just patched it in the latest release. Try downloading 1.1.3 and trying that instead. Hopefully there won't be any save file conflicts (I don't think there should be). Let me know if it worked!

**Comment by gomamisomix** [comment]
This is 1.1.3, The puzzle looks correct. 
![20200814141428_1](https://user-images.githubusercontent.com/5131918/90216173-d4ec1d00-de38-11ea-83a2-deec15aad211.jpg)
Thanks sigma144!

**Comment by sigma144** [comment]
Great, I'm glad it worked! However I anticipate there might be other puzzles later on where this might happen. You also might get a crash on the Keep blue pressure plate puzzle. I think I have a better handle on this problem now, and I'm working on a more permanent fix. I'll close the issue once it gets taken care of. Thanks again for all the information; you've been super helpful!

**Comment by sigma144** [comment]
I did some digging and found that the only other puzzles that should possibly be able to have this issue in 1.1.3 are the pillar puzzles at the very end of the game, and that one blue puzzle in the Keep. They should be fixed in 1.1.4, so just download that if you experience any further problems. Hopefully that's the last we'll see of this bug!
