### ISSUE TITLE
Unsolvable puzzle in the Quarry

### ISSUE THREAD

**Issue by sat1212** [sigma144/witness-randomizer#18]
I have an unsolvable puzzle in the quarry, after going up the stairs that drop down.  The seed is 283917 on version 1.1.5.  I tested it with the solver.

![The Witness 10_26_2020 8_24_48 PM](https://user-images.githubusercontent.com/68836225/97245833-edc66680-17c9-11eb-8129-befdb25ade8a.png)

**Comment by instr3** [comment]
Hi,

I think this level is solvable (see the spoiler below). Probably some issue with the solver?

<details>
  <summary>Spoiler warning</summary>
  
![image](https://user-images.githubusercontent.com/13694510/97409414-8975e500-1938-11eb-9ba4-76027682c325.png)

  
</details>

**Comment by sat1212** [comment]
Your solution worked.  Thank you, my brain would only let me imagine the star being canceled.

**Comment by sigma144** [comment]
Yay, I'm glad someone was able to help! Sorry about the solver though. I'm not sure why the solver seems to be inconsistent with the eraser symbols. I'd love to fix it, but I haven't looked at the solver source code in ages, and right now I want to prioritize the mod itself. I'll probably try to update the solver for version 2 of the randomizer whenever it comes out.
