### ISSUE TITLE
Mountain: Green Monitor Puzzle Impossible Tetromino?

### ISSUE THREAD

**Issue by ZZKer** [sigma144/witness-randomizer#20]
Seed: 84067
On the top floor of the Mountain, the 3rd puzzle in the green monitor series has a tetromino that does not solve. It appears to be a 4-square sideways, backwards L, but does not solve no matter what shape it is part of. Even trying to just get the shape to not blink while disregarding the rest of the puzzle does not work.
![broken_puzzle](https://user-images.githubusercontent.com/9769576/98297027-d170b980-1f81-11eb-81b1-261d79112a67.png)

**Comment by sigma144** [comment]
Hi ZZKer, thanks for playing my mod! I tried this puzzle myself and found that the puzzle is solvable. Part of the tetris shape is just obscured by the panel. You'll notice that the tetris symbol seems a little off-center in the square, which can clue you in that some part of it is covered up. Click below if you'd like to see one possible solution.

<details>
  <summary>Click to see solution</summary>
  
![Capture](https://user-images.githubusercontent.com/3487299/98453555-7927ec00-2128-11eb-950f-e1f08fe1f1e2.PNG)
  
</details>
