### ISSUE TITLE
Keep Laser Behavior

### ISSUE THREAD

**Issue by jeffreybardon** [sigma144/witness-randomizer#24]
Specifically on Normal difficulty, the Keep laser can be activated by solving the front half to access the tower, then climbing up and solving the back panel. In the vanilla game, the back panel isn't active until solving the 4th maze, and on Expert, something else (the 2nd maze?) activates it. This strikes me as an unintended possibility and would likely be best to return tying the back laser panel to solving the 4th (symmetry) maze, assuming that it's impossible to only have it activate after solving all 4 through activating/deactivitating.

**Comment by sigma144** [comment]
Thanks for the report. I've noticed that glitch in the past, but didn't know it was still happening. I'll get on that soon.

**Comment by sigma144** [comment]
This should now be fixed in version 1.1.7.
