### ISSUE TITLE
Address found: 0x62d0a0

### ISSUE THREAD

**Issue by Timmifutz** [sigma144/witness-randomizer#30]
Am I doing this right? :D

**Comment by sigma144** [comment]
Thanks for the info, Timmifutz! Was this on the same version of the Witness that you usually play on, or a different version? If so, can you tell me where you got this version from?

**Comment by sigma144** [comment]
Actually nvm, I already have this pointer in the list so it must have been a one-time memory glitch. I'll keep this in mind if it happens again. Thanks for the report!
