### ISSUE TITLE
How can the panel on the shipwreck be solved?

### ISSUE THREAD

**Issue by LeavingLeaves** [sigma144/witness-randomizer#31]
Those dots never match the sound

**Comment by LeavingLeaves** [comment]
emm... i realized that the color was changed, that's why i can get through it
red + yellow = orange, red + cyan = pink, and we always control the cyan line in symmetric panel. but in this panel i control yellow line, which really confused me

**Comment by sigma144** [comment]
Hi LeavingLeaves! Was this on Normal or Expert you experienced this issue?

**Comment by LeavingLeaves** [comment]
> Hi LeavingLeaves! Was this on Normal or Expert you experienced this issue?

on Expert

**Comment by sigma144** [comment]
Thanks. This week will be too busy for me but I'll take a look at it next week for sure. The puzzle should still be solvable at least, since the Shipwreck puzzle for some reason doesn't seem to care which line you use to collect the orange/pink dots.

**Comment by sigma144** [comment]
Ok...so apparently the game was programmed so that cyan=orange and yellow=pink for this puzzle. Very weird. I'll flip them in the next patch. Thanks for the report!

**Comment by sigma144** [comment]
Fixed in version 1.2.
