### ISSUE TITLE
Error trying to open

### ISSUE THREAD

**Issue by ScorpionBlack111** [sigma144/witness-randomizer#34]
hello I already installed it and when I open it I get this error, you know if there is any solution
![image](https://user-images.githubusercontent.com/83838349/117494956-53638e80-af75-11eb-8f20-e322e6ce1dde.png), shortly after he tells me that it has not been possible and that I comment here the error

**Comment by sigma144** [comment]
Hey there! Which operating system were you using, and where did you get this version of The Witness? Also I've seen this error happen randomly even though everything is fine, so I'd recommend trying to run the randomizer a second time if you haven't already.

**Comment by ScorpionBlack111** [comment]
I have Windows 10, and the version of the witness i don´t know how to see it, but since I bought it on ps4 I didn't want to buy it again to test mods, it´s pirate from mediafire (idk how to say it in english properly xd)

**Comment by sigma144** [comment]
Thanks. Have you tried running the randomizer again? If that doesn't work, I'll try to include a better pointer finder in the next patch.

**Comment by ScorpionBlack111** [comment]
I just tried again and it still gets the same error, I will wait for that patch. Thanks for your attention :)

**Comment by sigma144** [comment]
I tried expanding the range of possible pointer values to search through in version 1.2. It will probably pop up that error again but hopefully this time it will be able to find the globals ptr. Let me know what happens when you get a chance to test it.

**Comment by ScorpionBlack111** [comment]
I'm sorry it took so long to answer, i just tested it with 1.2.3 and it tells me the same

**Comment by sigma144** [comment]
Ok. The original mod creator darkid came up with a fix that might correct this. I can probably incorporate it this week or next week. I'll release a new version and then hopefully it will work for you then. Thanks for your patience.

**Comment by ScorpionBlack111** [comment]
Thanks to you for being active and attending to proposals and errors. I will try that new fix :D

**Comment by sigma144** [comment]
I posted version 1.2.4 in the releases section. Let me know if it works for you. If that doesn't work, try running WitnessRPG1.2.4.exe in administrator mode, in case Windows permissions is blocking it for some reason.

**Comment by ScorpionBlack111** [comment]
Hi sigma 144, I tried and it starts but when i check the first puzzle they got an error, this one is out of frame, not visible and not letting me interact with it
![The Witness Screenshot 2021 11 19 - 00 08 25 95](https://user-images.githubusercontent.com/83838349/142511208-be8c4f6c-b345-43d8-ad0f-7d7e9af4ff67.png)

**Comment by sigma144** [comment]
Very strange. Where did you get this version from again? I'm probably going to have to test it myself to figure out the issue. BTW I was able to download the GOG version from somewhere and it worked fine for me with the mod. So that might be something to try out.

**Comment by ScorpionBlack111** [comment]
i got the game on this page https://freegogpcgames.com/901/the-witness/

**Comment by sigma144** [comment]
I just tested the version from that link you sent, and it's working fine for me. Are you using the 32-bit or 64-bit version of Windows 10? Also, try doing it with directly launching the executable file witness64_d3d11.exe. If that doesn't work I'd suggest downloading the version of the Witness from the link you provided, since it should be compatible with the mod.

**Comment by sigma144** [comment]
Going to close this for now due to lack of activity, and because I haven't been able to reproduce the issue.
