### ISSUE TITLE
Address found 0x62d0a0

### ISSUE THREAD

**Issue by Zimodo** [sigma144/witness-randomizer#35]
I got this error message after deleting the previous version of the randomizer and installing the new one, and running it for the first time.

Address found: 0x62d0a0. This address will be automatically loaded next time. Please post an issue on Github with this address so that it can be added in the future.

![](https://cdn.discordapp.com/attachments/700566713644744737/848195794649481226/unknown.png)

**Comment by sigma144** [comment]
Thanks for the report. I have that memory address in the list already, but for some reason it randomly fails sometimes. I'll keep this issue here for now as a reminder to fix this problem at some point.

**Comment by sigma144** [comment]
I added a memory check to hopefully make it more reliable to find the globals ptr on startup. Don't know if it fixed it but I'll close this for now until the issue pops up again.
