### ISSUE TITLE
Swamp bridge puzzle shuts off after reloading (Expert)

### ISSUE THREAD

**Issue by karl2883** [sigma144/witness-randomizer#38]
After solving the tutorial puzzles, the bridge puzzle and a few puzzles after that and reloading the world + randomizer, the bridge panel (the first one with the straight bridge) just shuts off. You can still see the lit cable on the right. Re-solving the last tutorial puzzle in the swamp helps, but after solving the bridge puzzle again and reloading it's off again. 
Seed: 155077 (Expert)

![Screenshot (29)](https://user-images.githubusercontent.com/66829803/124507424-1594b200-ddce-11eb-91ad-4a8e427cd894.png)

**Comment by sigma144** [comment]
Thanks for the report! I'll have this fixed in the next patch.

**Comment by karl2883** [comment]
I think there is the same issue with the church puzzle (where you'd normally see through the yellow glass).

**Comment by sigma144** [comment]
Fixed in version 1.2.
