### ISSUE TITLE
Sort off impossible puzzle?

### ISSUE THREAD

**Issue by mpg0907** [sigma144/witness-randomizer#41]
![impossible puzzle](https://user-images.githubusercontent.com/51968382/127930518-f0dfda6b-c24d-4e4f-aeb7-6514086e5ab4.jpg)
in the swamp i found this puzzle. every intersection has a hexogonal dot.
your solver and the game find this sollusion a good awnser but you still block the place of the tetris shape with a line. should this be the case or not cause it feels impossible logicaly.

**Comment by medicatedshawnie** [comment]
This is intended behavior, the line is allowed to cut through pieces so long as they still fit in the region

**Comment by mpg0907** [comment]
ah ok. good to know.
