### ISSUE TITLE
Unsolvable puzzles in Swamp

### ISSUE THREAD

**Issue by vampirestrike** [sigma144/witness-randomizer#42]
Found two puzzles in the Swamp that were unsolvable. Both were in the drained portions with negative Tetris pieces.
![20210811172813_1](https://user-images.githubusercontent.com/88802887/129106080-cf5255d1-4eeb-45f4-b003-dcf87a9adab7.jpg)
![20210811172733_1](https://user-images.githubusercontent.com/88802887/129106083-8b2e52dd-4d9f-4155-96e7-51fab80418b3.jpg)
Seed is 517308. Solver came up with no solutions as well, for both.

**Comment by instr3** [comment]
They are both solvable. The solver has some issues I guess.
![image](https://user-images.githubusercontent.com/13694510/129288196-68a2c40e-5f3d-4c11-b84f-59cd6f1b50fb.png)
![image](https://user-images.githubusercontent.com/13694510/129288393-98849f26-b8a9-433c-af5d-ba537d77137d.png)

**Comment by vampirestrike** [comment]
In some cases I've been using the solver to check to make sure there is a possible solution (when I'm stuck). Guess I shouldn't have given up. Thanks.
