### ISSUE TITLE
Seemingly impossible puzzle (not even the solver can solve it)

### ISSUE THREAD

**Issue by Wynter-del** [sigma144/witness-randomizer#50]
Normal difficulty, seed: 295368.
Location: The Mountain, top floor, green checkerboard puzzles.

The tetromino is the problem here. As it wants a diagonal piece which obviously cannot work. I've recreated the puzzle in the solver, and it can't find a solution.
![image](https://user-images.githubusercontent.com/74967400/145638222-99014d5b-fd9f-4811-9674-a3c08483a5d0.png)

I thought that maybe the black checkerboard is perhaps obscuring a possible "L" shape, as that would make the puzzle solvable, yet when I attempt that, the puzzle marks the tetromino as being invalid:
![image](https://user-images.githubusercontent.com/74967400/145638369-b9da112f-8907-44f5-bf38-ccefbc0085b3.png)

From what I can tell, the randomizer has generated an impossible puzzle. I'll complete the puzzle without the randomizer, but I think it's worth pointing out that it somehow managed to allow an impossible puzzle through.

**Comment by sigma144** [comment]
Hi Wynter-del! Based on the positioning of the symbol, it looks like it is a pentomino L. So this solution should work: RRUULLUURRDRDDDRUUUU. Let me know if you encounter any more potential issues! The randomizer is fairly stable at this point, so all puzzles should be solvable. The solver on the other hand might not always work, but the randomizer doesn't use it anyway, it's just a potential aid for players.
