### ISSUE TITLE
Broken puzzles generated in quarry

### ISSUE THREAD

**Issue by TadCordle** [sigma144/witness-randomizer#51]
Just got this puzzle in the quarry:
![image](https://user-images.githubusercontent.com/521881/147311472-7a1744d2-e0aa-4e05-9077-f3ec970e2a31.png)

I tried this solution several times, and sometimes it works:
![image](https://user-images.githubusercontent.com/521881/147311530-a6c5a6df-9dd2-4809-b25e-1cd4d0093488.png)

But sometimes it doesn't:
![image](https://user-images.githubusercontent.com/521881/147311576-6cb65662-0fde-45d8-8174-46e6735f8708.png)

**Comment by TadCordle** [comment]
Sorry, just realized I'm not on the latest version... maybe a bug that was already fixed?

**Comment by medicatedshawnie** [comment]
![unnamed](https://user-images.githubusercontent.com/60412657/147319187-78a5afe3-b1f5-495d-a17b-e60dbfdba675.png)
The correct solution is shown above

**Comment by TadCordle** [comment]
I guess this is more a problem with the base mechanic and not the randomizer, then. Just seems weird to me that you can draw a line that works "sometimes".
