### ISSUE TITLE
Panel in Desert not turning on

### ISSUE THREAD

**Issue by Iwastheturkey3** [sigma144/witness-randomizer#52]
the last panel in the third underground section wont turn on.   Ive tried resolving all the other panels in order with the randomizer off and reloading the game.   
all other panels solved
![witness64_d3d11_2JMlDDS9MS](https://user-images.githubusercontent.com/20333452/152574120-e73f96fb-12f7-4b26-aeb2-5bfa91ac1289.jpg)
this one is still off
![witness64_d3d11_O1UdEBTnne](https://user-images.githubusercontent.com/20333452/152574158-1badeead-02ba-43c8-b7e4-d33870dbad55.jpg)

**Comment by sigma144** [comment]
In rando, that panel is activated by the floating panel at the back of the room. Try running the rando and _then_ solving (or resolving) that panel. If it doesn't work let me know the seed and I'll look at it 👍
