### ISSUE TITLE
Issue: Castle Pressure Plate Puzzle Generated with Unsolvable Layout

### ISSUE THREAD

**Issue by Stiggles** [sigma144/witness-randomizer#59]
Using seed Normal: 236236 in the castle pressure plate walkway mazes.

The third maze has an environmental break and a section of line with an implied hex (Edit: or no break and two sections with implied hexes). Both contributed to the generation of an unsolvable puzzle. Confirmed as impossible with the solver. (There's also no way to reroute around certain sections of this specific puzzle, that makes it very likely there are many other unsolvable layouts. Similarly the second and fourth puzzle in this section may also fall into this category as both have restricted movement from environmental hazards Edit: In this specific seed, both puzzles 2 and 4 of this section are solvable,.)

Puzzle location (Top left in this image)
![20220411104222_1](https://user-images.githubusercontent.com/5864144/162764447-88d0d896-ed5a-454b-b8f4-6e75f5783c32.jpg)

Image of environmental break:
![20220411103645_1](https://user-images.githubusercontent.com/5864144/162763624-95e8927d-c6cb-4f4e-891b-9f946925f1d5.jpg)

Image of implied hex:
![20220411103842_1](https://user-images.githubusercontent.com/5864144/162763691-6c17545b-0b35-4ab4-8baf-ebdc7000e9e3.jpg)

Solver confirmed unsolvable:
![Screenshot 2022-04-11 104003](https://user-images.githubusercontent.com/5864144/162764076-f281de0a-37bd-4417-8d5d-2aa94b131f85.png)

Solvable without those hazards in place:
![Screenshot 2022-04-11 104051](https://user-images.githubusercontent.com/5864144/162764156-896eb0a9-cf3e-47b1-91b0-c7cff49abae1.png)

**Comment by MarugawaDK** [comment]
This puzzle is solvable:

...**SPOILER ALERT**...? hehe

![witness-keep-236236](https://user-images.githubusercontent.com/87547987/162808329-97efc6a0-1ddc-43cc-9e9e-aaaa3ea8b870.png)

**Comment by Stiggles** [comment]
> This puzzle is solvable:

Thank you for this. I think I found the solution, though it requires pixel hunting at the reset slide from the 4th line in the back. (I couldn't even seen the start dot on the reset from that far back.)

**Comment by MarugawaDK** [comment]
No problem.

You can also do it from the start/first row, since you can just backtrack (after hitting the obstruction) and then scoot across at the parallel lines in the third row. But yeah, both works.

**Comment by sigma144** [comment]
Puzzle was confirmed to be solvable.
