### ISSUE TITLE
Issue with double-output puzzle that has effects based on output choice

### ISSUE THREAD

**Issue by Nova-Ardent** [sigma144/witness-randomizer#62]
Seed 1: Expert
Seed 2: Expert

Both seeds have issues with the double-output puzzle for the gate on the back left side of the castle from the start; I think the system assumes it found a solution for 1 output and that is fine, but both outputs are required for progression.

**Comment by MarugawaDK** [comment]
It is intentional.

It is mentioned in the  ["Known Issues"](https://github.com/sigma144/witness-randomizer/wiki/Known-Issues#tutorial-1), under "Expert Difficulty" > "Tutorial" > "Two Exit Puzzle".
