### ISSUE TITLE
Unsolvable Puzzle in Normal Randomizer

### ISSUE THREAD

**Issue by quixQuery** [sigma144/witness-randomizer#69]
I have closed and reopened a doubled randomizer file, so this issue may just be rehashing the same things, but I don't know enough to tell.
This puzzle has no solution, as you can tell by the pair mechanic shapes having odd numbers. 
Difficulty:Normal 
Seed:1337 
Options:Double
Witness RPG Version 1.3.0

![image](https://user-images.githubusercontent.com/26725961/177639619-1fe3d948-6cea-415b-9771-111ad1024e1b.png)

**Comment by sigma144** [comment]
Ah, looks like it's the Town Star Door puzzle. Which means you'd normally look through it through the yellow glass in Town. It is still solvable in double, but you would need to figure out what the true colors would be.
