### ISSUE TITLE
MastΣr ModΣ

### ISSUE THREAD

**Issue by BLSK** [sigma144/witness-randomizer#70]
And yes that is a Sigma Symbol for 'Master'... Thought it was a cute touch:

**Most Expert Rules Still Apply**
**Optional Panels Might Not Be Optional**
Arriving at a Main Panel and finishing it Might not Activate the Next One in a Chain.
**Added Symbol:  The Wall**
A line lies up against a side of a square section in grid up to all four sides and you may not pass by it.  It is similar to a gap... more of a reverse triangle... but.... You Shall Not Pass!  Very shy such walls, but with a little color they may like to find friends hanging around.
![TheWall](https://user-images.githubusercontent.com/8443396/180908371-9575e185-5efc-47fc-8c10-d3c648f40310.png)

**Puzzles of Hell**
Expert is hard... but what if the Arrows and even 'The Wall' were not limited by mere mortal bounds of 'Triangles'.  Optionals would be easy enough and possible force the Starter Zone to have a nice friendly puzzle to throw 'The Wall' in a person's Face Right off the bat!(A extra big slighly complicated Σ on 2nd door wishing good luck a good place for 'The Wall'?)
Outside of that a tiny tweek to maybe include more shapes on the board.  Don't know how it goes but possibly ramp up the difficulty a teensy weensy bit?  But I hope 'The Wall' would add some potential challenge on it's own if it was allowed to run free across the whole world!

Haven't really thought of much more to make it harder... unless even laser activations might be scrambled onto 'any puzzle' on the map with high chance of 'deep puzzles progression'(hopefully excluding caves...softlock)  Optionals might activate 'forward progress' such as GBRsoundProof Door.  Not like Double Random... just literally... some paths might be closed off by the Optionals instead of 'unlocking non-random' stuff.  The Puzzles would be normal(ish) for the area, but Optionals may be need to complete even be needed to light up your first Tetris Door.  Just rambling but yes That all sounds could... if it could happen XD.

Just a thought... not sure what can be done... but thanks for reading... I think it could be interesting and harder than Expert.  Just an idea :)
BLSK

**Comment by sigma144** [comment]
Thanks for the suggestions! There have been a number of additional game mode suggestions and new symbols, and I'll probably bundle them all in to one of the future version I make.

**Comment by sigma144** [comment]
We've got a lot of extra modes made by other people by now (including Variety rando and Despair rando) so I'm probably not adding any more modes to the main randomizer. Hopefully these other modes will satisfy people looking for a change from the regular randomizer.
