### ISSUE TITLE
Unsolvable puzzle in first area

### ISSUE THREAD

**Issue by veedeeee** [sigma144/witness-randomizer#71]
![image](https://user-images.githubusercontent.com/11916394/184479617-ba791a2c-99d5-4989-ac4b-a1f289ad0dbe.png)
Seed: Expert 2744769
I believe I cannot solve 4 dots of right-bottom corner cuz if I take A-B-D-Goal I cannot go over C, also if I take (A)-C-D-Goal I cannot pass on B.

Surely I can go upper goal but I cannot go lower goal then I can't open glowing cage :(

**Comment by MarugawaDK** [comment]
This is intentional, try solving the glowing gate some other way. ;)

(also this is mentioned in the known issues)
