### ISSUE TITLE
Puzzle won't accept a particular valid solution

### ISSUE THREAD

**Issue by supernova1987b** [sigma144/witness-randomizer#72]
![image](https://user-images.githubusercontent.com/111813046/186029965-8f38e63f-2ee3-43ba-bbc4-8c4447e10b16.png)
This is the solution that I got it to accept.  But this:
![image](https://user-images.githubusercontent.com/111813046/186030040-34bc5b1c-bf77-44ca-9f59-017d1c86965c.png)
is the solution I first found (and the solution the solver produces).  It will not accept that solution:
![image](https://user-images.githubusercontent.com/111813046/186030254-c48870d8-b8e2-44d7-9ef5-c3999b8d23ca.png)

Seed 451, normal difficulty, puzzle is under the teal water in the swamp area.

**Comment by supernova1987b** [comment]
Just found another one in the same area.  
![image](https://user-images.githubusercontent.com/111813046/186030978-9ff251c1-6ab0-4f6b-8199-9bb99dd6214d.png)

Again, this happens to be the solution that the solver produces.  I'm sure there's another solution but I'm still looking for it.

**Comment by sigma144** [comment]
This is an issue with the game's logic when checking shapes. Solutions will only be accepted if all of the shapes fit inside of the grid _before_ canceling out any pieces. So in that last case for example, the disconnected shape would have to extend partially off of the bottom of the grid before removing the 3 diagonal pieces, so it's not considered valid. There will always be a solution the game will accept, so it's just a matter of keeping in mind where you can put the shapes. Hope this helps!

**Comment by sigma144** [comment]
You can find more details at https://github.com/sigma144/witness-randomizer/wiki/Known-Issues
