### ISSUE TITLE
Blank puzzle panel in treehouse area

### ISSUE THREAD

**Issue by supernova1987b** [sigma144/witness-randomizer#73]
I am playing the randomizer with seed 1337 in Expert Mode.  The second-to-last puzzle I need to do in the treehouse area is just black:
![image](https://user-images.githubusercontent.com/111813046/187108887-7d397f47-ed6d-40e4-ab47-425114da5ddc.png)
This problem persists after changing the direction of the platforms, re-solving the previous platform, quitting the game, and even while unrandomized:
![image](https://user-images.githubusercontent.com/111813046/187108956-9b21a759-78a7-422c-aad8-7c35fca6072b.png)

Clicking on the square "focuses" the camera on the panel as normal, but I tried clicking all over and couldn't find any way to interact with it.  

I also replayed from my previous save file up to this point; the panel is still blank.  The fact that the puzzle panel is still blank while unrandomized leads me to believe that there's a problem in the save file, maybe?  Here are my two most recent save files, in case that helps.
[bugged saves.zip](https://github.com/sigma144/witness-randomizer/files/9441100/bugged.saves.zip)

Going a bit insane about this because I was hoping to see what crazy stuff would be in expert-mode Caves, and the treehouse area is the second-to-last laser; I'm already so deep into this seed!

**Comment by sigma144** [comment]
It's actually supposed to be like that! It turns on after you activate the Treehouse laser.
