### ISSUE TITLE
Impossible puzzle?

### ISSUE THREAD

**Issue by dackid19** [sigma144/witness-randomizer#75]
![image](https://user-images.githubusercontent.com/41722896/190033284-6499084b-92b0-461f-98cd-f565b969806f.png)
Correct me if I am wrong, but I don't see an end here. I think it is obstructed by the tv borders

**Comment by dackid19** [comment]
Oh boy! Yea, this is a common theme. There are many puzzle panels that are unsolvable because the panels are too small and the endpoints are out of reach.

**Comment by sigma144** [comment]
This appears to be the same issue as #67. It mainly happens on repeated double randos. One workaround is to exit the game, repoening and randomizing again. I have an idea for a bug fix but want to get other things done first. Thanks for reporting, and let me know if you still have issues after the workaround!

**Comment by sigma144** [comment]
Same issue as #67
