### ISSUE TITLE
Randomizer not working (Again)

### ISSUE THREAD

**Issue by Mushycatt** [sigma144/witness-randomizer#77]
![image](https://user-images.githubusercontent.com/113127401/195907726-23a5f533-eccf-47aa-a95c-7ae2cf28185a.png)

Hi, sorry for bothering with this problem again!
Last time the problem really was the name change (don't know how that even happened), but now I really don't understand why it doesn't work:
Both the game's and the randomizer's versions are up to date, the name is the same as you suggested, I tried opening the game straight from the exe and running the RPG in administrator but to no avail.
Any help would be appreciated!

**Comment by sigma144** [comment]
So you changed the name, it started working for a bit, and now it's not working again? Or were you never able to get it to run in the first place?

**Comment by Mushycatt** [comment]
yeah, exactly that, so thank you for last time.

**Comment by Mushycatt** [comment]
oops accidentally closed, sorry I'm bad at github

yeah, exactly what you said has happened. it might be useful for you to know that it stopped working right after I accidentally moved the RPG file to another location, but then ctrlZ ed it to move it back. I have since also deleted and re-installed the RPG, but it did nothing

**Comment by sigma144** [comment]
Huh, I have no idea why that would happen. And you tried uninstalling and reinstalling the game already? Are you making sure you are running the 64-bit witness exe and not the 32 bit one? If you happen to have the Epic games version from the Epic games giveaway, please also try testing it on that.

**Comment by Mushycatt** [comment]
Ok I uninstalled and reinstalled The Witness. I have it on steam, I checked in the files, I am opening the game's exe which has 64 in it's name

Maybe it's just something with the names? Can we go over the names again? Is the folder itself supposed to have a specific name in order to work?

**Comment by sigma144** [comment]
All it does is look for a running process with the name "witness64_d3d11.exe". It doesn't matter which folder the rando or game is in. I don't know if I mentioned this, but also make sure the game is fully booted up before opening the randomizer.

**Comment by Mushycatt** [comment]
![image](https://user-images.githubusercontent.com/113127401/196058466-20bdcc48-141a-4c33-8edf-7f413ec94b08.png)
the games pretty much loaded up I mean I can move around and everything...
here's a screenshot of everything. any idea?

**Comment by sigma144** [comment]
Hmm, not sure why it's showing the witness exe in your randomizer folder. You should leave all the witness files where they are, are you shouldn't need to rename any files. Here's one more idea to try: see if version 1.3.0 works. You can download it from the releases page.

**Comment by Mushycatt** [comment]
Oh nonono I didn't move any Witness files, that's just the task manager showing The Witness is active
Will try to download 1.3.0. I'll update, thanks!

**Comment by Mushycatt** [comment]
Bad news - it didn't work... older versions act exactly the same. just to be sure I clicked verify file integrity in the witness but it's all good

**Comment by Mushycatt** [comment]
Any idea on what I can do?

**Comment by sigma144** [comment]
Sorry, I don't know what would be causing this. But I can make a debugging build to send you next week, which some extra logging that might help me figure out what's going on.

**Comment by Mushycatt** [comment]
That'll be great! tysm

**Comment by MarugawaDK** [comment]
Just a thought, could there be some Windows security setting or anti-virus that doesn't allow programs to see other running processes? (i.e. the issue could've come from an automatic system/anti-virus update)

Also, I don't know if something like compatibility mode could affect the inter-process visibility? Like if the game and the randomizer are running in different compatibility modes...?

But, It's probably more likely that it's related to whatever caused the previous issue. But again, just a thought.

**Comment by sigma144** [comment]
I'm wondering that too. Admin mode didn't work. But I will get a version ready with some logging that might help. I can probably have that up tomorrow.

**Comment by sigma144** [comment]
I put up a new release at [](https://github.com/sigma144/witness-randomizer/releases/tag/1.3.1-Logging). Can you try it out and send me the output.txt that it generates?

**Comment by sigma144** [comment]
Okay don't know where my line went lol. Its https://github.com/sigma144/witness-randomizer/releases/tag/1.3.1-Logging

**Comment by Mushycatt** [comment]
Ok I tried it and this exe now does work??? And I didn't change the name or anything

**Comment by sigma144** [comment]
Well I'm glad that fixed it! if it happens again I'll try sending a new exe again.
