### ISSUE TITLE
Impossible Constraint

### ISSUE THREAD

**Issue by envy2000** [sigma144/witness-randomizer#80]
Seed: 636574
Difficulty: Expert
Symmetry (Coast) 5th Puzzle
![20230122195456_1](https://user-images.githubusercontent.com/63881241/213954014-7843029a-acb9-48d6-8e21-dbcd581d3b0f.jpg)
One of the cells has 4 triangles, which is an unsolvable clue

**Comment by Exempt-Medic** [comment]
I recommend checking the hints section when you are stuck. Trust the randomizer, this panel is not impossible. Try solving it and you will see
