### ISSUE TITLE
Door issue in town?

### ISSUE THREAD

**Issue by Rainbow-skys** [sigma144/witness-randomizer#81]
For expert randomizer (seed 9391318) Solved the puzzle on the yellow stained glass door in the town, but when I put it in the door didn’t open. Is this intentional? I think I’ve done most of the other things in the town already. 
My solve for the door was UURDDRRRUULLULLURRURRDDRUU

**Comment by Exempt-Medic** [comment]
This is intended, you'll have to solve the nearby suns panel outside the church to open that door.
