### ISSUE TITLE
"Impossible" puzzle in Caves (according to the solver)

### ISSUE THREAD

**Issue by Maziodyne** [sigma144/witness-randomizer#82]
Played on Normal, seed was 341799. Got this impossible puzzle in Caves:

![shot_2023 05 05__time_20_37_n01](https://user-images.githubusercontent.com/66443777/236593776-5bbbe371-5172-44d1-91de-2d319631b709.png)

I even threw the puzzle into the solver, and the solver returned "No solutions found".

**Comment by MarugawaDK** [comment]
It is solvable.

<details><summary>SPOILER ALERT:</summary>
<p>
ULLURRRDDDLLULDDRRRRUUUU
</p>
</details>

**Comment by Maziodyne** [comment]
![shot_2023 05 06__time_12_50_n01](https://user-images.githubusercontent.com/66443777/236636895-ac27bbc7-5c6f-4600-a23f-8e12ba348d1a.png)

I guess this is more of an issue with the solver, then. Just to show what happens when I give this puzzle to the solver:

![Solver found nothing](https://user-images.githubusercontent.com/66443777/236636957-f4b94342-4207-4eec-b9bd-ce3762e6a612.png)

**Comment by Exempt-Medic** [comment]
The solver that comes with the rando has several errors and differences. They are aware of, at this point, I'm sure just about every single one of these
