### ISSUE TITLE
Possible randomization for the currently non-randomized puzzles (except Greenhouse)

### ISSUE THREAD

**Issue by R3Ked** [sigma144/witness-randomizer#83]
I don't know a whole lot about how the randomization in this game works, so sorry if this is literally impossible, but I have an idea for how to randomize areas that depend on the environment. Instead of randomizing the environment, it may be possible to take the panels themselves and turn them into normal puzzles that don't depend on the environment. Maybe even incorporate a few new symbols, like arrows.

**Comment by sigma144** [comment]
Thanks for your suggestion! The Witness community has been working on ways to randomize the environment, so I plan to go with that for the next version.
