### ISSUE TITLE
Impossible puzzle in the mountain

### ISSUE THREAD

**Issue by R3Ked** [sigma144/witness-randomizer#84]
![image](https://github.com/sigma144/witness-randomizer/assets/20342336/43d870ee-9320-455e-a562-09b375a4cefe)
Unless I inputted it wrong, this is impossible.

Seed: 7592686

**Comment by MarugawaDK** [comment]
I don't think you'll be able to do the multi-stage puzzles with the solver. It's going to expect that you need to solve it with a single line - which probably would be impossible - however... I think this should work:

![image](https://github.com/sigma144/witness-randomizer/assets/87547987/68dca178-ffd6-4e6a-a2df-47071d39be20)

**Comment by R3Ked** [comment]
I need to solve it with one line and getting to a top exit to even use the second line in the first place.

**Comment by Exempt-Medic** [comment]
The solver failed, it happens. The process that MarugawaDK outlined will perfectly solve this panel. First you draw the red line and use it to walk across. Then you solve the green side, as shown and walk back across the red line which you then unsolve and solve with the blue line.
