### ISSUE TITLE
Panel in Desert won't turn on

### ISSUE THREAD

**Issue by R3Ked** [sigma144/witness-randomizer#85]
![image](https://github.com/sigma144/witness-randomizer/assets/20342336/96246187-bdc3-4f06-8da8-9df06bc33889)
I derandomized for the third(?) panel to solve it with a guide, but this panel wouldn't turn on even after I re-randomized. Am I stuck?

**Comment by R3Ked** [comment]
I got all 5, no clue what's wrong.

**Comment by R3Ked** [comment]
Ok, I don't know what I did, but it just turned on. I didn't solve anything new. What.

**Comment by sigma144** [comment]
It had been reported that panels in Desert act strange on rare occasions. It may or may not be related to this issue, so I'll leave this here for now to remind me about it in case we ever discover a fix.

**Comment by sigma144** [comment]
Haven't gotten any other reports about this in a while, so I'm going to assume the changes to Desert and memory operations probably fixed it.
