### ISSUE TITLE
Impossible Puzzle in Caves

### ISSUE THREAD

**Issue by zyzzvays** [sigma144/witness-randomizer#86]
Seed: 719462, Difficulty: Normal
Location: Caves, Door to Challenge
![20230625222428_1](https://github.com/sigma144/witness-randomizer/assets/135754189/afd1952e-fae0-4bc4-88be-0d202a5d09d9)
I put it through a solver, and it returned no solution.

**Comment by MarugawaDK** [comment]
Seems possible to me: (but there might be a bug in the solver, wouldn't be the first time)

![image](https://github.com/sigma144/witness-randomizer/assets/87547987/3aa59aa3-196b-4f0f-9190-4afbcc6d85c8)

**Comment by zyzzvays** [comment]
I had only encountered adjacent tetris block sets in one other puzzle and would have not found that solution myself. I tested it and it did work.
