### ISSUE TITLE
Image Glitches

### ISSUE THREAD

**Issue by CrystalStream** [sigma144/witness-randomizer#87]
![20230626193713_1](https://github.com/sigma144/witness-randomizer/assets/137785285/bd062a29-0ee9-425c-8d4c-63e532946102)
![20230626193936_1](https://github.com/sigma144/witness-randomizer/assets/137785285/cf442eeb-55e7-4622-a462-67688b1e1dda)
(But when I start solving the puzzle, the problem board becomes normal)

**Comment by sigma144** [comment]
Thanks for reporting! The panel shuffle/double rando setting is not yet designed to work perfectly with repeated play sessions. There's already a Github issue about this, so I'll close this one.
