### ISSUE TITLE
Unable to click puzzle in desert

### ISSUE THREAD

**Issue by AutumnRivers** [sigma144/witness-randomizer#88]
[YouTube Video showcasing bug](https://youtu.be/MJCp74lDsmI)

Seed: 5011865. Normal randomization.

Every other puzzle works fine, and it seems to load. Can't click on it whatsoever though, as it just does not respond.

![Screenshot 2023-07-16 222718](https://github.com/sigma144/witness-randomizer/assets/26543607/4111fb8d-c716-44e9-b57c-a0b3b182422c)

**Comment by sigma144** [comment]
Thanks for reporting! The panels is Desert have been reported to have issues on rare occasions. It mostly seems to happen on repeat playthroughs. I already have an Github issue open for fixing Desert, so I'll close this one for now.
