### ISSUE TITLE
Potential unsolvable Keep pressure plate puzzle, Expert mode

### ISSUE THREAD

**Issue by the-jay** [sigma144/witness-randomizer#89]
I can't find a solution and neither can the solver. Am I wrong, or is this an oversight, because I don't see a way to get to the top side of the puzzle without breaking it.

Expert seed 2563440

![image](https://github.com/sigma144/witness-randomizer/assets/174139/5ba8748c-eb4b-4515-8abf-188212eb7c47)

![image](https://github.com/sigma144/witness-randomizer/assets/174139/98dbe780-5691-4b04-9047-f455046ca228)

![image](https://github.com/sigma144/witness-randomizer/assets/174139/320f3794-c1a2-4f66-92ee-01f125d0359a)

**Comment by MarugawaDK** [comment]
I think you might need to solve the mazes out of order.

**Comment by the-jay** [comment]
Yeah, figured it out right after assuming it was impossible, as usual. 🤦‍♂️
