### ISSUE TITLE
Town Tower Door When Solving Perspective Panel First (v 1.0.7)

### ISSUE THREAD

**Issue by medicatedshawnie** [sigma144/witness-randomizer#9]
In Town I solved the red perspective panel and _then_ the panel with lots of multi-color suns and the first door to the tower would not open. The only way I found to open it was to shut down the game and solve the perspective panel without the randomizer being on. (I am aware of how this section ordinarily works with the randomizer but it seems like solving them "in the wrong order" prevents the door from opening) The two panels I'm talking about are visible in the following picture:
![SPOILERS](https://user-images.githubusercontent.com/60412657/75633923-35630700-5bd7-11ea-8eb7-bf8e031fe67f.PNG)

**Comment by instr3** [comment]
I think it is intended. In expert mode finishing these three puzzles is not enough to open the first door to the tower. Try to find other puzzles that you missed.

**Comment by medicatedshawnie** [comment]
Hmm, yeah it might be the case that you also have to solve the triple-color lights panels (that's the only one I hadn't done). If that's the case, consider this closed.
