### ISSUE TITLE
Unsoveabe Puzze in symmetry pennisua

### ISSUE THREAD

**Issue by oneandonlyflexo** [sigma144/witness-randomizer#92]
I have run the 1.3.1 version of the witness randomizer on the current version of the witness with expert mode and seed `6191667`.  Everything was working just fine until I ended up getting an unsolveable puzzle in the symmetry pennisula

![broken ranodomized puzzle](https://github.com/sigma144/witness-randomizer/assets/1873556/849ad2b3-1bfc-4f44-a548-313b4e9bf063)

![Equivaent puzze in witness solver](https://github.com/sigma144/witness-randomizer/assets/1873556/fde6138e-2f09-4175-8014-67752623d740)

**Comment by Exempt-Medic** [comment]
![SOLVE](https://github.com/sigma144/witness-randomizer/assets/60412657/231a1b4d-6c0f-48d6-9f04-3c9c5b076bcd)
Those images do not match, here's a solution

**Comment by oneandonlyflexo** [comment]
Ah you're absolutely right.  The solver works if you don't double up on the single triangles in the shared middle column.  If you try the different options for whether the left or right hand line gets them, then it ends up working just fine even.
