### ISSUE TITLE
Unsolvable Puzzle

### ISSUE THREAD

**Issue by M-AAA** [sigma144/witness-randomizer#94]
I found an unsolvable puzzle. Information:

- Playing on Expert Double Mode
- Seed 3684482
- Located in The Swamp, first puzzle in the set next to the stairs going down into the red water
![fsfssf](https://github.com/sigma144/witness-randomizer/assets/54368600/46810a36-0da8-4cbf-8eee-3450d1d33b94)

**Comment by Exempt-Medic** [comment]
![SOLVE](https://github.com/sigma144/witness-randomizer/assets/60412657/1b427214-386a-441a-ba1c-d751dbe58e06)

**Comment by M-AAA** [comment]
Whoops. The solver couldn't find it so I assumed it wasn't possible
