### ISSUE TITLE
Potential unsolvable Puzzle with multiple ends

### ISSUE THREAD

**Issue by rnharmening** [sigma144/witness-randomizer#97]
I think the following puzzle cannot be completed with the bottom end:

seed 1516 Expert Mode (no options)
in stating area

![image](https://github.com/sigma144/witness-randomizer/assets/22399399/f6ab030b-ca67-439b-8b42-a1ecc95144aa)

The two marked nodes are of degree 2, but share the same neighbors. This makes it impossible to pass both (while not ending at one of them).

**Comment by Exempt-Medic** [comment]
You are correct, it cannot be solve to the bottom end. This is intended

**Comment by rnharmening** [comment]
Thank, that was a quick reply!
