### ISSUE TITLE
Randomizer not working

### ISSUE THREAD

**Issue by pcaston2** [sigma144/witness-randomizer#98]
I installed The Witness (GoG)

I run the game, run the randomizer, it gives me an error about the pointer being wrong, it finds it anyway, with this message:

---------------------------
Error
---------------------------
Address found: 0x5d1180. This address wil be automatically loaded next time. Please post an issue on Github with this address so that it can be added in the future.
---------------------------
OK   
---------------------------

When I click "Randomize" it shows "Randomizing" but then quits when it's done. When I have the randomizer open it says it should be left open so I don't think it is supposed to close?

When I go back to the game it is unchanged.

With Expert and Double Mode, when would I encounter the first evidence of a change? Would it be in the starting tunnel?

This could entirely be me making a mistake but I think I followed the instructions.

**Comment by sigma144** [comment]
I've tested the randomizer on the GoG version before and it seemed to work fine. You'll know it worked if the very first panel looks different. If you still weren't able to get it to run, reply to this issue and I can see what I can do.

**Comment by pcaston2** [comment]
Almost a year later, giving this another try.

I get this error on first run, might be related:

---------------------------
Error
---------------------------
Address found: 0x5d1180. This address wil be automatically loaded next time. Please post an issue on Github with this address so that it can be added in the future.
---------------------------
OK   
---------------------------

I am using GoG v.10671


Whenever I load the randomizer, I get this as a seed:
1058869599
It could be that the first time I ran it I typed this and this is out of range, but it uses this anyway. How do I wipe out the setting that this is saved in? I wiped some Witness save files, started a new game, deleted the randomizer and reunziped it.

---------------------------
Error
---------------------------
Please enter a number between 1 and 9999999.
---------------------------
OK   
---------------------------
I get this error so it thinks the seed it out of range.

I start a new game, it crashes, I relaunch, new game, launch the randomizer, it remembers that seed and it still thinks the game has that seed. I change the seed to something else (eg. 1) and hit randomize.

The first door in the bunker teleports to the bottom left corner and I can't click on it. It doesn't say the seed or difficulty.
