### ISSUE TITLE
Correct Solution Invalid?

### ISSUE THREAD

**Issue by brddsfnhsdfbjs** [sigma144/witness-randomizer#99]
![Screenshot 2024-06-09 174636](https://github.com/sigma144/witness-randomizer/assets/129024865/d6d323d3-3307-48f6-a9db-2d2f1aadbc0b)

In this puzzle, the desired solution wants me to use the Y elimination mark to cancel out the pink outlined Tetris block, to make one whole shape, but why can I not use the Y elimination mark to cancel out the top left Tetris piece, and remove the block on the right Tetris block as shown in my image.

Thanks

**Comment by MarugawaDK** [comment]
I believe that this is because the original shape would go outside of the bounds of the puzzle. Or you can think about it like the minus blocks also have to be "inside the puzzle".

**Comment by Exempt-Medic** [comment]
MarugawaDK is correct https://github.com/sigma144/witness-randomizer/wiki/Known-Issues#swamp
